version: 1.7.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
os: Visual Studio 2015
configuration: Release
platform:
- x86
- x64
- ARM
before_build:
- cmd: nuget restore openhabUWP.sln
build:
  project: openhabUWP.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '**/*.appx'
